import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background:{
    flex:1,
    backgroundColor:'black',
  },
  calculadoraContainer:{
    flex:1,
    paddingHorizontal:20,
    justifyContent:'flex-end',
  },
  resultado:{
    color:'white',
    fontSize:60,
    textAlign:"right",
    marginBottom:10
  },
  resultadoFloat:{
    color:'rgba(255,255,255,0.5)',
    fontSize:30,
    textAlign:"right",
  },
  fila:{
    flexDirection:'row',
    justifyContent:'center',
    marginBottom:18,
    paddingHorizontal:10
  },
  boton:{
    marginHorizontal:10,
    height:80,
    width:80,
    borderRadius:100,
    justifyContent:'center',
  },
  botonTexto:{
    textAlign:'center',
    padding:10,
    fontSize:30,
    color:'white',
    fontWeight:'300'
  }
});